[tool.poetry]
name = "bilibili"
version = "0.1.0"
description = ""
authors = ["icebear <969549808@qq.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
rich = "^13.6.0"
black = "^23.10.1"
requests = "^2.31.0"
sqlalchemy = "^2.0.22"
pydantic = "^2.4.2"
pre-commit = "^3.5.0"
fake-useragent = "^1.3.0"
click = "^8.1.7"


[tool.poetry.group.dev.dependencies]
ipython = "^8.17.2"
ruff = "^0.1.5"
ruff-lsp = "^0.0.44"
black = "^23.11.0"
pre-commit = "^3.5.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
