# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff mypy coverage
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: ruff
        run: |
          ruff . --fix --exit-non-zero-on-fix
      - name: mypy
        run: |
          mypy bilibili conf core utils main.py
      - name: Run code coverage
        run: |
          coverage run -m unittest discover -s tests
          coverage report xml

      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v3