name: Publish

on:
  push:
    tags:
      - '*'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "1.7.1"
      - name: Publish
        run: |
          poetry install
          poetry config repositories.pypi https://upload.pypi.org/legacy/
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
          poetry build
          poetry publish 
